baseURL = "https://lq7.tw/"
languageCode = "zh-tw"
title = "LQ7 | 以創作和思考探索世界"
theme = "PaperMod"

[params]
  author = "LQ7"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  disableSpecial1stPost = true

  [params.homeInfoParams]
    Title = "LQ7 在此向您打招呼！"
	Content = """
大家好，我是LQ7，本職為資訊工程師，同時也是個自由創作者，喜愛各種形式的藝術創作。

這裡有我的小說作品，以及我的日常興趣——  
包括寫作、音樂、動漫、遊戲、運動、魔術與哲學等主題上的心得與思考。

如果當中有任何感興趣的內容，歡迎隨意逛逛。  
有任何感想都可以填寫[意見表單](https://forms.gle/y8tJ5kNVEyk9V1BN7)，期待收到您的回饋！
"""

[menu]
  [[menu.main]]
    name = "二創小說"
    url = "/fanfic/"
    weight = 10

  [[menu.main]]
    name = "寫作習慣"
    url = "/writing/"
    weight = 20

  [[menu.main]]
    name = "閱讀心得"
    url = "/reading/"
    weight = 30

  [[menu.main]]
    name = "生活思考"
    url = "/thinking/"
    weight = 40

  [[menu.main]]
    name = "心情隨筆"
    url = "/mood/"
    weight = 50

  [[menu.main]]
    name = "關於我"
    url = "/about/"
    weight = 60
