baseURL = "https://lq7.tw/"
languageCode = "zh-tw"
title = "LQ7 | 寫作與故事"
theme = "PaperMod"

[params]
  author = "LQ7"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  disableSpecial1stPost = true

[menu]
  [[menu.main]]
    name = "創作"
    url = "/fiction/"
    weight = 10
  [[menu.main]]
    name = "創作筆記"
    url = "/notes/"
    weight = 20
  [[menu.main]]
    name = "閱讀筆記"
    url = "/reading/"
    weight = 30
  [[menu.main]]
    name = "生活側記"
    url = "/journal/"
    weight = 40
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 50
