baseURL = "https://lq7.tw/"
languageCode = "zh-tw"
defaultContentLanguage = "zh-tw"
title = "LQ7的創作與想像"
theme = "PaperMod"
timeZone = "Asia/Taipei"
hasCJKLanguage = true
[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
[markup.goldmark.renderer]
  unsafe = true
[pagination]
  pagerSize = 10

[params]
  author = "LQ7"
  defaultTheme = "dark"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  disableSpecial1stPost = true
  ShowFullTextinRSS = true
  ShowWordCount = true
  mainSections = ["fanfic", "writing", "reading", "thinking", "mood","tech","event","music"]
  defaultImage = "https://lq7.tw/images/default-banner.png"
  
  [params.label]
  text = "LQ7的創作與想像"
  icon = "/images/avatar.png"
  iconHeight = 35

  [params.homeInfoParams]
    Title = "LQ7 在此向您打招呼！"
    Content = """
　　大家好，我是LQ7，從事資訊相關工作，同時也是個自由創作者，喜愛各種形式的藝術。這裡有我閒暇之餘的興趣，包括小說、寫作、音樂、動漫、哲學、魔術、遊戲與運動等主題上的心得與思考。如有任何感興趣的內容，歡迎隨意逛逛。喜歡的話，也可以透過 [RSS 訂閱](https://lq7.tw/index.xml) 追蹤本站更新。

　　有任何感想歡迎使用[意見表單](https://forms.gle/y8tJ5kNVEyk9V1BN7)或[寫信給我](mailto:lpseven@gmail.com)，或在[留言板](/guestbook/)簽個名，期待收到您的回饋 ( ・∀・)ﾉ
"""
[params.footer]
  hidePoweredBy = true
  text = "LQ7 版權所有"

[menu]
  [[menu.main]]
    name = "全部"
    url = "/list/"
    weight = 5
  [[menu.main]]
    name = "小說"
    url = "/fanfic/"
    weight = 10

  [[menu.main]]
    name = "寫作"
    url = "/writing/"
    weight = 20
	
  [[menu.main]]
    name = "音樂"
    url = "/music/"
    weight = 25

  [[menu.main]]
    name = "閱讀"
    url = "/reading/"
    weight = 30

  [[menu.main]]
    name = "思考"
    url = "/thinking/"
    weight = 40

  [[menu.main]]
    name = "心情"
    url = "/mood/"
    weight = 50
	
  [[menu.main]]
    name = "活動"
    url = "/event/"
    weight = 53
  [[menu.main]]
    name = "技術"
    url = "/tech/"
    weight = 54
	
  [[menu.main]]
    name = "留言板"
    url = "/guestbook/"
    weight = 55

  [[menu.main]]
    name = "關於我"
    url = "/about/"
    weight = 60
